[build]
builder = "NIXPACKS"
dockerfilePath = ""

[deploy]
startCommand = "node migrate.js; npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
